#!/bin/bash

print_status() {
    echo "$1"
}

exec_cmd_nobail() {
#    echo "+ $1"
    bash -c "$1"
}

exec_cmd() {
    exec_cmd_nobail "$1" || bail
}

branch="stable"
repo="redhat"
title="Redhat"
name="ih-systems"
keyring="/usr/share/keyrings"
key_url="http://rpm.ih-systems.com/ih-systems.gpg"
local_key="$keyring/ih-systems.gpg"

if [ "$1" == "beta" ]; then
  branch="beta"
fi


print_status "Creating yum sources list file for the ${name} repo..."

exec_cmd "echo -e '[${name}]\nname=${name} repository\nbaseurl=http://rpm.ih-systems.com/${repo}/${branch}\nenabled=1\ngpgcheck=1\ngpgkey=http://rpm.ih-systems.com/ih-systems.gpg' > /etc/yum.repos.d/${name}.repo"

print_status "Complete!"
