#!/bin/bash

print_status() {
    echo "$1"
}

exec_cmd_nobail() {
#    echo "+ $1"
    bash -c "$1"
}

branch="stable"
repo="redhat"
title="Redhat"
name="ih-systems"
keyring="/usr/share/keyrings"
key_url="http://rpm.ih-systems.com/ih-systems.gpg"
local_key="$keyring/ih-systems.gpg"

if [ "$1" == "beta" ]; then
  branch="beta"
fi

if grep -qs "centos" "/etc/os-release"; then
  repo="centos"
  title="CentOS"
fi

if grep -qs "redos" "/etc/os-release"; then
  repo="redos"
  title="RED OS"
fi

if grep -qs "fedora" "/etc/os-release"; then
  repo="fedoralinux"
  title="Fedora Linux"
fi

if grep -qs "altlinux" "/etc/os-release"; then
  repo="altlinux"
  title="ALT Linux"
fi

print_status "Creating yum sources list file for the ${name} repo..."

exec_cmd_nobail "echo -e '[${name}]\nname=${name} repository\nbaseurl=http://rpm.ih-systems.com/${repo}/${branch}\nenabled=1\ngpgcheck=1\ngpgkey=http://rpm.ih-systems.com/ih-systems.gpg' > /etc/yum.repos.d/${name}.repo"

print_status "Complete!"
